"""add updated at to properties

Revision ID: 3fcfed18d0ab
Revises: 8cb9d1eee985
Create Date: 2026-09-14 13:30:51.354547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcfed18d0ab'
down_revision: Union[str, Sequence[str], None] = '8cb9d1eee985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('updated_at', sa.DateTime(
        timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'updated_at')
    # ### end Alembic commands ###
