"""add image url to properties

Revision ID: 65dbeb9c12de
Revises: b8d82310f972
Create Date: 2026-09-13 18:36:56.117969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65dbeb9c12de'
down_revision: Union[str, Sequence[str], None] = 'b8d82310f972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'image_url')
    # ### end Alembic commands ###
