"""add property status

Revision ID: ac8b8027134f
Revises: 4a1e9b7cdf3e
Create Date: 2026-10-01 17:39:15.337302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8b8027134f'
down_revision: Union[str, Sequence[str], None] = '4a1e9b7cdf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'properties',
        sa.Column(
            'status',
            sa.String(length=30),
            nullable=False,
            server_default="planned"
        )
    )

    op.alter_column(
        "properties",
        "status",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'status')
    # ### end Alembic commands ###
