"""add loan entries

Revision ID: c71a26a2060b
Revises: 96326562f919
Create Date: 2026-10-07 17:11:04.401216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71a26a2060b'
down_revision: Union[str, Sequence[str], None] = '96326562f919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_entry_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['diary_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diary_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_entries')
    # ### end Alembic commands ###
