"""add market value to properties

Revision ID: f5101b07daaf
Revises: 3fcfed18d0ab
Create Date: 2026-09-15 20:34:04.215455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5101b07daaf'
down_revision: Union[str, Sequence[str], None] = '3fcfed18d0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('market_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'market_value')
    # ### end Alembic commands ###
