"""add utility entries

Revision ID: fe28a49d1354
Revises: c71a26a2060b
Create Date: 2026-10-08 17:01:29.026353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe28a49d1354'
down_revision: Union[str, Sequence[str], None] = 'c71a26a2060b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_entry_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['diary_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diary_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility_entries')
    # ### end Alembic commands ###
